name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4000-4010:4000-4010"
      - "3001:3001"
    volumes:
      # Use bind mount for better I/O performance
      - /home/ubuntu/hl:/home/ubuntu/hl:rw
      - ../hl:/home/hluser/hl:rw
      - /tmp/hl_snapshots:/tmp/hl_snapshots:rw
      - ./override_gossip_config.json:/home/hluser/override_gossip_config.json:ro
    command: ["--serve-info", "--write-fills", "--write-raw-book-diffs","--write-order-statuses", "--batch-by-block", "--disable-output-file-buffering", "--serve-eth-rpc"]
    environment:
      - RUST_BACKTRACE=full
    # Performance optimizations
    network_mode: host
    ipc: host
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    mem_limit: 58g
    mem_swappiness: 0
    # Reduce container overhead
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    
  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - /home/ubuntu/hl:/home/hluser/hl:rw
    # Run with lower priority
    cpu_shares: 256
    
volumes:
  hl-data:
    driver: local
