name: "hyperliquid-prod"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4000-4010:4000-4010"
      - "3001:3001"
    volumes:
      # Use tmpfs for order status files (in-memory)
      - type: tmpfs
        target: /home/hluser/hl/data/node_order_statuses
        tmpfs:
          size: 4g
      # Bind mount for persistent data
      - ./hl-data:/home/hluser/hl:rw
      - ./override_gossip_config.json:/home/hluser/override_gossip_config.json:ro
    command: ["--write-order-statuses", "--disable-output-file-buffering"]
    # Maximum performance settings
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
      memlock:
        soft: -1
        hard: -1
      rtprio:
        soft: 99
        hard: 99
    # Dedicated resources
    cpuset: "0-7"
    mem_limit: 32g
    memswap_limit: 32g
    mem_swappiness: 0
    oom_kill_disable: true
    # Minimal logging
    logging:
      driver: "none"
    # Performance tuning
    environment:
      - GOGC=100
      - GOMAXPROCS=8
    sysctls:
      - net.core.rmem_max=134217728
      - net.core.wmem_max=134217728
      - net.ipv4.tcp_rmem=4096 87380 134217728
      - net.ipv4.tcp_wmem=4096 65536 134217728
      - net.core.netdev_max_backlog=5000
    
  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - ./hl-data:/home/hluser/hl:rw
    # Run with lower priority
    cpu_shares: 128
    nice: 19
    
  # Orderbook service running outside Docker for best performance
  # Directly accesses bind-mounted hl-data directory