name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4000-4010:4000-4010"
      - "3001:3001"
    volumes:
      - hl-data:/home/hluser/hl
      - ./override_gossip_config.json:/home/hluser/override_gossip_config.json
    command: ["--write-order-statuses", "--disable-output-file-buffering"]
  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - hl-data:/home/hluser/hl
volumes:
  hl-data:
    driver: local